//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CustomerDetails()
        {
            this.tbl_CustomerDocuments = new HashSet<tbl_CustomerDocuments>();
            this.tbl_CustomerFlatDetails = new HashSet<tbl_CustomerFlatDetails>();
        }
    
        public int ProjectId { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerDocuments> tbl_CustomerDocuments { get; set; }
        public virtual tbl_ProjectDetails tbl_ProjectDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerFlatDetails> tbl_CustomerFlatDetails { get; set; }
    }
}
