//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerDocuments
    {
        public int CustomerId { get; set; }
        public int CustomerDetailss { get; set; }
        public byte[] Pan { get; set; }
        public byte[] Aadhar { get; set; }
    
        public virtual tbl_CustomerDetails tbl_CustomerDetails { get; set; }
    }
}
