//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCDApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerFlatDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CustomerFlatDetails()
        {
            this.tbl_CustomerTransactionDetails = new HashSet<tbl_CustomerTransactionDetails>();
        }
    
        public int CustomerId { get; set; }
        public int CusFlatId { get; set; }
        public int TotalFlatSqft { get; set; }
        public int TotalValue { get; set; }
    
        public virtual tbl_CustomerDetails tbl_CustomerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CustomerTransactionDetails> tbl_CustomerTransactionDetails { get; set; }
    }
}
